version: '2'

services:
  db:
    image: mysql
    container_name: mysqldb
    command: mysqld --user=root --verbose
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    tty: true
  armateam:
    build: ./armateam
    container_name: armateam
    hostname: armateam
    ports:
      - "80:80"
      - "2333:22" # ssh
      - "8787:8484"
    expose:
      - "9000"
    links:
      - db:mysqldb
    volumes:
      - ./armateam/src:/home/src
      - ./logs/nginx/:/var/log/nginx
      - ./logs/symfony:/home/src/tournament/var/logs
      - ./logs/symfony:/home/src/bookshop-api/var/logs
    tty: true
  elk:
    image: willdurand/elk
    container_name: elk
    ports:
        - 8181:80
    volumes:
        - ./elk/logstash:/etc/logstash
        - ./elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - armateam
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8282:80
    links:
      - db
    tty: true